# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: secret.SECRET_KEY
      PYTHONPATH: './src/'

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES: off
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: install pipenv
      run: |
        sudo apt-get install libpq-dev -y
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev
        pipenv run pre-commit install --hook-type commit-msg

    - name: migrate
      run: pipenv run python src/manage.py migrate

    - name: lint
      run: pipenv run pre-commit run flake8 -a

    - name: Test with pytest
      run: |
        pipenv run coverage run --source='./src' -m pytest --suppress-no-test-exit-code
